all:
    hosts:
        icu_server:
            ansible_host: 188.166.249.118
            ansible_user: root
            ansible_ssh_private_key_file: ~/.ssh/id_ed25519
            ansible_python_interpreter: /usr/bin/python3
