all:
  hosts:
    production:
      ansible_host: 188.166.249.118  
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
  
  vars:
    # Domain names
    frontend_dev_domain: icu-dev.darwishathibi.com
    frontend_prod_domain: icu.darwishathibi.com
    backend_dev_domain: icu-api-dev.darwishathibi.com
    backend_prod_domain: icu-api.darwishathibi.com
    
    # Application settings
    deploy_user: deployer
    app_directory: /opt/apps
    
    # Docker registry
    docker_registry: ghcr.io
    github_username: darwishathibi 